# Generated by Django 5.1.4 on 2025-01-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='video',
            name='premiere_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
