# Generated by Django 5.1.4 on 2025-01-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_background_image_video_premiere_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='premiere',
        ),
        migrations.AddField(
            model_name='video',
            name='movie_type',
            field=models.CharField(blank=True, choices=[('Movie', 'Movie'), ('TV Series', 'TV Series')], max_length=50, null=True),
        ),
    ]
