# Generated by Django 5.1.4 on 2025-01-04 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('videos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='actors_set', to='videos.video'),
        ),
        migrations.AddField(
            model_name='director',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='directors', to='videos.video'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
