# Generated by Django 5.1.4 on 2025-01-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='actor_photos/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_photos', to='users.actor')),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='photos_album',
            field=models.ManyToManyField(blank=True, related_name='actors', to='users.actorphoto'),
        ),
    ]
