# Generated by Django 5.1.4 on 2025-01-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_actorphoto_actor_photos_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photos_album',
            field=models.ManyToManyField(blank=True, related_name='albums', to='users.actorphoto'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='actor_photos/profile'),
        ),
        migrations.AlterField(
            model_name='actorphoto',
            name='photo',
            field=models.ImageField(upload_to='actor_photos/album'),
        ),
    ]
