# Generated by Django 5.1.4 on 2025-01-06 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_actor_photos_album_alter_actor_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='director_photos/profile'),
        ),
        migrations.CreateModel(
            name='DirectorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='director_photos/album')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_photos', to='users.director')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='photos_album',
            field=models.ManyToManyField(blank=True, related_name='albums', to='users.directorphoto'),
        ),
    ]
